# Generated by Django 5.2.7 on 2025-11-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='month',
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.student'),
        ),
    ]
