# Generated by Django 5.2.7 on 2025-11-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_student_remove_fee_date_remove_fee_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
