# Generated by Django 5.2.7 on 2025-11-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fee_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='Student_name',
        ),
    ]
