# Generated by Django 5.2.7 on 2025-11-07 14:53

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudentandFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(choices=[('Programming', 'Programming'), ('Robotics', 'Robotics'), ('AI', 'AI'), ('Training', 'Training')], default='Robotics', max_length=100)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
