# Generated by Django 5.2.7 on 2025-11-08 01:52

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_addstudentandfee_delete_fee_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeacherandPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('Programming', 'Programming'), ('Robotics', 'Robotics'), ('AI', 'AI'), ('Training', 'Training')], default='Robotics', max_length=100)),
                ('Contactnumber', models.CharField(blank=True, max_length=15, null=True)),
                ('pay_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
