# Generated by Django 5.2.7 on 2025-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_addteacherandpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='addteacherandpay',
            name='pay_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
