# Generated by Django 5.2.7 on 2025-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_addteacherandpay_pay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Furniture', 'Furniture'), ('Lab Equipment', 'Lab Equipment'), ('Electronics', 'Electronics'), ('Stationery', 'Stationery')], default='Furniture', help_text='Select main category', max_length=50)),
                ('sub_item', models.CharField(help_text='Specify sub-item (e.g., Chair, Microscope)', max_length=100)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in Rs', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Half Paid', 'Half Paid'), ('Pending', 'Pending')], default='Pending', help_text='Payment status: Paid, Half Paid, Pending', max_length=20)),
            ],
        ),
    ]
