# Generated by Django 5.2.7 on 2025-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_assests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assests',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Pending', help_text='Payment status: Paid, Partial Pending', max_length=20),
        ),
    ]
