# Generated by Django 5.2.7 on 2025-11-20 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_assests_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Furniture', 'Furniture'), ('Lab Equipment', 'Lab Equipment'), ('Electronics', 'Electronics'), ('Stationery', 'Stationery')], default='Furniture', help_text='Select main category', max_length=50)),
                ('sub_item', models.CharField(help_text='Specify sub-item (e.g., Chair, Microscope)', max_length=100)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost in Rs', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Pending', help_text='Payment status: Paid, Partial, Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Utilities', 'Electricity / Utilities'), ('Refreshments', 'Snacks / Tea'), ('Stationery', 'Notes / Printing'), ('Maintenance', 'Repairs / Maintenance'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', help_text='Select main category (e.g., Utilities, Snacks)', max_length=50)),
                ('description', models.CharField(help_text='Specify details (e.g., October Bill, Tea for Guests)', max_length=100)),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date when expense occurred')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost in Rs', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Paid', help_text='Payment status: Paid, Pending', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload receipt image (optional)', null=True, upload_to='receipts/')),
            ],
        ),
        migrations.DeleteModel(
            name='Assests',
        ),
    ]
